### ISSUE TITLE
CORSエラーが発生している

### ISSUE THREAD

**Issue by akifumiakifumi** [KEN-ALL/kenall-js-demo#20]
![CapturFiles_806](https://github.com/user-attachments/assets/d671e5f2-8ae0-465a-a078-f21fdeec552a)

**Comment by yukimi821** [comment]
@akifumiakifumi ご報告ありがとうございます。

`REACT_APP_KENALL_API_KEY` で指定した API キーの編集画面から、 `Originヘッダー設定` で該当のドメイン名 (今回は `localhost:3000`) をご指定ください。ご指定の際はポート番号まで含めてください。
詳しくはドキュメントの [API キーの管理](https://kenall.jp/docs/account/api-key/#api%E3%82%AD%E3%83%BC%E3%82%92%E7%B7%A8%E9%9B%86%E3%81%99%E3%82%8B) をご参照ください。
また、 [よくある質問 > トラブルシューティング](https://kenall.jp/docs/faq/#%E3%83%88%E3%83%A9%E3%83%96%E3%83%AB%E3%82%B7%E3%83%A5%E3%83%BC%E3%83%86%E3%82%A3%E3%83%B3%E3%82%B0) にも記載がございますので、上記で解決しない場合はこちらをご参照ください。 (一部リンク切れがございますので修正いたします)

README に Origin ヘッダ設定について追記したいと思います。
ご指摘ありがとうございました。

**Comment by akifumiakifumi** [comment]
@yukimi821 
こちらの設定ミスにも関わらずご丁寧にご返信いただきありがとうございました🙇‍♂️
こちらCloseしたいと思います
